# Generated by Django 4.2.3 on 2023-07-31 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginSystemApp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserInfo',
        ),
    ]
